#<MustBeenWind>
from library_for_glad_ai_tors import*
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW=False
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY=True
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu=None
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY=len
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu=dir
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYW=abs
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKueW=int
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKueY=range
def start(arg):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWYe(arg)
 return("XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWe",XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWe(arg):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW='XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWe'
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWYe(arg)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['LAUNCH']=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('time_to_turn')<=0:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('x_dir',1 if random()<0.3 else 2 if random()<0.3 else 0)
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('y_dir',1 if random()<0.3 else 2 if random()<0.3 else 0)
  if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir')==0 and XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir')==0:
   if random()<0.5:
    XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('x_dir',1 if random()<0.5 else 2)
   else:
    XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('y_dir',1 if random()<0.5 else 2)
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY)
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW)
  if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeK(get_position(arg),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWe(arg),150):
   XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('x_dir',1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir')==2 else 1)
  if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeK(get_position(arg),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWe(arg),150):
   XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('y_dir',1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir')==2 else 1)
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('time_to_turn',3)
 if random()<0.07:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW='XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY'
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('time_to_turn',3)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYe(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYW(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKe(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,rand=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW)
 return(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY(arg):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW='XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY'
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWYe(arg)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['LAUNCH']=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('time_XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY_remaining')<=0:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW='XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWe'
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('time_XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY_remaining',10)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYu=999
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'])>0:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'][XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'])//2]['angle']
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWK(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY)
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('x_dir',XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWKe(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY['x'],XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY))
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('y_dir',XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWKe(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKWY['y'],XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW))
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYu=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'][XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'])//2]['dist']
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('time_XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY_remaining',XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('time_XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY_remaining')-1)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYe(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYW(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY)
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYu>60:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKe(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
 else:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKe(0,0,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
 return(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYe(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWKY(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW)
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW<=1:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['LAUNCH']=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKYW(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir'),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW)
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeK(get_position(arg),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWe(arg),100):
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('x_dir',1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('x_dir')==2 else 2)
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeK(get_position(arg),XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKuY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWe(arg),100):
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK('y_dir',1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY('y_dir')==2 else 2)
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWuK=1
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWuY=1
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWKu=200
XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWKY={'enemy_x':'A','enemy_y':'B','enemy_angle':'C','enemy_dist':'D','x_dir':'E','y_dir':'F','time_to_turn':'G','time_XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKWY_remaining':'H','I':'I','J':'J'}
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeK(position,direction,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,borders,padding=40):
 if direction is XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu:
  return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW
 if direction=='n' and position[1]-padding<=borders['n']:
  return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
 if direction=='s' and position[1]+padding>=borders['s']:
  return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
 if direction=='e' and position[0]+padding>=borders['e']:
  return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
 if direction=='w' and position[0]-padding<=borders['w']:
  return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
 for XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYu in XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['obstacle']:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWK(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYu['angle'])
  if direction in 'ns':XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK['y']
  if direction in 'ew':XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK['x']
  if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYK==direction:
   if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWYu['dist']<padding:
    return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuY
 return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWeY(num,is_x):
 if is_x:
  return 'e' if num==2 else 'w' if num==1 else XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu
 else:
  return 'n' if num==1 else 's' if num==2 else XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWKe(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu,is_x):
 if is_x:
  return 2 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu=='e' else 1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu=='w' else XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu
 else:
  return 2 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu=='s' else 1 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYu=='n' else XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWu
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWKY(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK=get_weapon_angle(arg)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent']
 cc=0
 cw=0
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuW)<=0:
  return 100
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'][XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeWY(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY['opponent'])//2]
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuW['angle']
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeYW(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK-XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu)
 cc=(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW<180 and XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu>XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK)or(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW>180 and XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu<XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK)
 cw=(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW<180 and XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu<XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK)or(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW>180 and XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKu>XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYuK)
 cc=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKueW(cc)
 cw=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKueW(cw)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKW=1
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW<=1:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKW=0
 elif XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW<20:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKW=0.3
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ROT_CC']=cc*XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKW
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ROT_CW']=cw*XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYKW
 return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeKYW
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWYe(arg):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW={}
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYWu=get_weapon_power(arg)>80
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['CHARGE']=not XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYWu
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['SHIELD']=not XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYWu
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKW(arg)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK={}
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY=lambda varname:XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYeK(varname,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,arg)
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK=lambda varname,varval:XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYeW(varname,varval,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK)
 return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuYK
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuWYK(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKW,val,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYWK,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeYWK[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKW]=val
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWKY[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKW]]=val
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYeK(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK,arg):
 if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY not in XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY]=get_saved_data(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWKY[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY])
 return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY]
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYeW(XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY,val,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuWK[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY]=val
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWKY[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueKY]]=val
 return val
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKe(x,y,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW,slow=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW,rand=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKeuW):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_Y']=0
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_X']=0
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWK=0.5 if slow else 1
 if y==1:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_Y']=-XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWK*(random()+0.4 if rand else 1)
 if y==2:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_Y']=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWK*(random()+0.4 if rand else 1)
 if x==1:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_X']=-XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWK*(random()+0.4 if rand else 1)
 if x==2:
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeuKW['ACLT_X']=XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWK*(random()+0.4 if rand else 1)
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYKW(arg):
 XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWY={'opponent':[],'obstacle':[]}
 for XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYK in XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOKueY(0,360,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOeWuY):
  XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYW,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKeW=get_radar_data(arg,XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYK)
  if XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYW:
   XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWY[XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYW].append({'dist':XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuKeW,'angle':XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueYK})
 return XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOueWY
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWe(arg):
 return{'n':get_n_border(arg),'e':get_e_border(arg),'w':get_w_border(arg),'s':get_s_border(arg)}
def XDtALnFfzvkGhQJwjBmMaUsiNrIbVRlqoTdHgExCpPycSOuYWK(angle):
 if angle<90 or angle>270:
  x='e'
 else:
  x='w'
 if angle<180:
  y='n'
 else:
  y='s'
 return{'x':x,'y':y}