#<Octorock>
from library_for_glad_ai_tors import*
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm=False
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi=True
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmf=None
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmi=len
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPif=abs
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPim=int
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNmfGi=range
def start(arg):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmPf(arg)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('time_to_turn',0)
 return("OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfi",OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi)
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfi(arg):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPi='OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfi'
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmPf(arg)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['LAUNCH']=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('time_to_turn')<=0:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('x_dir',1 if random()<0.3 else 2 if random()<0.3 else 0)
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('y_dir',1 if random()<0.3 else 2 if random()<0.3 else 0)
  if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir')==0 and OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir')==0:
   if random()<0.5:
    OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('x_dir',1 if random()<0.5 else 2)
   else:
    OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('y_dir',1 if random()<0.5 else 2)
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGi=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmif(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi)
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmif(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm)
  if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfP(get_position(arg),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPf(arg),150):
   OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('x_dir',1 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir')==2 else 1)
  if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfP(get_position(arg),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPf(arg),150):
   OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('y_dir',1 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir')==2 else 1)
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('time_to_turn',8)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('time_to_turn',OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('time_to_turn')-1)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmiP(arg,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi)
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG<=1:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['LAUNCH']=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGi=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmif(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmif(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm)
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfP(get_position(arg),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPf(arg),100):
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('x_dir',1 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir')==2 else 2)
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfP(get_position(arg),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmGP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPf(arg),100):
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm('y_dir',1 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir')==2 else 2)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGimf(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('x_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP('y_dir'),OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,rand=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm)
 return(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi)
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmPG=1
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmPi=1
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiGm=200
OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiGP={'enemy_x':'A','enemy_y':'B','enemy_angle':'C','enemy_dist':'D','x_dir':'E','y_dir':'F','time_to_turn':'G','H':'H','I':'I','J':'J'}
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmfP(position,direction,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,borders,padding=40):
 if direction is OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmf:
  return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm
 if direction=='n' and position[1]-padding<=borders['n']:
  return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 if direction=='s' and position[1]+padding>=borders['s']:
  return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 if direction=='e' and position[0]+padding>=borders['e']:
  return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 if direction=='w' and position[0]-padding<=borders['w']:
  return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 for OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimG in OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP['obstacle']:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPm(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimG['angle'])
  if direction in 'ns':OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP['y']
  if direction in 'ew':OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP['x']
  if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimP==direction:
   if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfimG['dist']<padding:
    return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfi
 return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmif(num,is_x):
 if is_x:
  return 'e' if num==2 else 'w' if num==1 else OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmf
 else:
  return 'n' if num==1 else 's' if num==2 else OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmf
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmiP(arg,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG=get_weapon_angle(arg)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPm=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP['opponent']
 cc=0
 cw=0
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPmi(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPm)<=0:
  return 100
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPm=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP['opponent'][0]
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPm['angle']
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPif(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG-OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm)
 cc=(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG<180 and OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm>OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG)or(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG>180 and OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm<OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG)
 cw=(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG<180 and OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm<OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG)or(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG>180 and OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGm>OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiPG)
 cc=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPim(cc)
 cw=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPim(cw)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGi=1
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG<=1:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGi=0
 elif OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG<20:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGi=0.3
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ROT_CC']=cc*OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGi
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ROT_CW']=cw*OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPGi
 return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmiG
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmPf(arg):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi={}
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPmG=get_weapon_power(arg)>80
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['CHARGE']=not OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPmG
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['SHIELD']=not OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPmG
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGimP(arg)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim={}
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP=lambda varname:OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGifm(varname,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim,arg)
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm=lambda varname,varval:OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGifP(varname,varval,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim)
 return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGiP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGPm
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGmPi(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPiG,val,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPmi[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPiG]=val
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiGP[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPiG]]=val
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGifm(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim,arg):
 if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim not in OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim]=get_saved_data(arg,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiGP[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim])
 return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim]
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGifP(OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim,val,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGim[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim]=val
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfiGP[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfPim]]=val
 return val
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGimf(x,y,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi,slow=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm,rand=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGPfm):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_Y']=0
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_X']=0
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmi=0.5 if slow else 1
 if y==1:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_Y']=-OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmi*(random()+0.4 if rand else 1)
 if y==2:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_Y']=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmi*(random()+0.4 if rand else 1)
 if x==1:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_X']=-OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmi*(random()+0.4 if rand else 1)
 if x==2:
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfGmi['ACLT_X']=OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmi*(random()+0.4 if rand else 1)
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGimP(arg):
 OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmP={'opponent':[],'obstacle':[]}
 for OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfim in OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNmfGi(0,360,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNfmPi):
  OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfiP,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfPm=get_radar_data(arg,OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfim)
  if OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfiP:
   OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmP[OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfiP].append({'dist':OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfPm,'angle':OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfim})
 return OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGfmP
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPf(arg):
 return{'n':get_n_border(arg),'e':get_e_border(arg),'w':get_w_border(arg),'s':get_s_border(arg)}
def OgBlHYjDrXxCzkJuaFyTUMKLsecIEWdtqnShoVbApQwvRNGiPm(angle):
 if angle<90 or angle>270:
  x='e'
 else:
  x='w'
 if angle<180:
  y='n'
 else:
  y='s'
 return{'x':x,'y':y}